### ISSUE TITLE
[User Stories MH] Google Maps

### ISSUE THREAD

**Issue by klementtan** [AY1920S1-CS2103T-T10-4/main#74]
As a member of a group project, I'd like to know where is the closest place for my group to meet, so that we will not waste time deciding where to meet.

## Conditions of satisfaction
- [x] Should be give the location that requires everyone traveling time to be the least

## Timeline create 
- [x] Create MVP
- [x] Create test case
- [x] Integrate to front end
