### ISSUE TITLE
As an NUSMods user, I'd like to import my NUSMods data 

### ISSUE THREAD

**Issue by marqueurs404** [AY1920S1-CS2103T-T10-4/main#76]
so that I do not have to manually create my schedule from scratch.

## Conditions of satisfaction

- [x] Should allow user to view a module details.
- [x] Should allow user to add his NUSMods timetable given an NUSMods share link.
- [x] Should allow user to add individual modules
- [x] Should be able to store NUSMods data offline for limited connectivity support
