### ISSUE TITLE
[User Stories NTH] Command Suggestions/Guidance

### ISSUE THREAD

**Issue by aidilfbk** [AY1920S1-CS2103T-T10-4/main#81]
As a forgetful user, I want to have some form of guidance when typing commands so that I can complete my command easily.

## Conditions of satisfaction

- [x] Should show all possible commands supported by the system
- [x] Should allow the user to pick their desired command from a list
- [x] Should automatically narrow down the possible commands based on user input
- [x] Should show relevant and valid parameter values for a command (e.g. `deletegroup` should show the current list of group names)
- [x] Should allow the user to pick a desired parameter value from a list
