### ISSUE TITLE
Wrap up time book

### ISSUE THREAD

**Issue by klementtan** [AY1920S1-CS2103T-T10-4/main#98]
Need to fully wrap up time book

# UI
- [1/2] Full test Case
- [x] Code Quality
- [x] UG
- [x] DG

# Tab auto complete
- [x] Full test Case
- [x] Code Quality
- [x] UG
- [x] DG

# Googlemaps
- [x] Full test Case
- [x] Code Quality
- [x] UG
- [x] DG

# Storage
- [x] Full test Case
- [x] Code Quality
- [x] UG
- [x] DG
